<x-slot:phead>Create A University </x-slot>

<div class="container-fluid">
    {{-- <div class="row">
        <div class="col-md-12">
            <div class="card shd">
                <div class="card-body">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb mb-0 py-0">
                            <li class="breadcrumb-item">
                                <a href="{{ route('welcome') }}">
                                    Home
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('dashboard') }}">
                                    Dashboard
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.homepage') }}#alert-link">
                                    previous
                                </a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                Edit
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div> --}}

    <div class="row">
        <div class="col-lg-12">
            <div class="card shd">
                <div class="card-header">
                    <h4 class="card-title">Country </h4>
                </div>
                <div class="card-body">
                    <form class="row g-2" wire:submit="create" novalidate>
                        <div class="col-12">
                            <label for="logo" class="form-label">Country Banner</label>

                            <input class="form-control @error('logo') is-invalid @enderror" id="logo"
                                type="file" required name="thumbnail" wire:model.blur="logo">
                            @error('logo')
                                <div id="logo" class="text-danger mt-1">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <div class="col-8">
                            <x-forms.text-input type="text" required name="university" wire:model.blur="university"
                                label="University Name" wire:keyup='generateSlug' />
                            @error('university')
                                <div id="university" class="text-danger mt-1">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        {{--  --}}
                        <div class="col-4">
                            <label for="country_id" class="form-label">Country</label>
                            <select class="form-select @error('country_id') is-invalid @enderror" required=""
                                aria-label="country_id" wire:model.live="country_id">
                                <option>University Loction</option>
                                @foreach ($countries as $country)
                                    <option value="{{ $country->country_id }}">
                                        {{ $country->country }}
                                    </option>
                                @endforeach
                            </select>
                            <div>
                                @error('country_id')
                                    <div id="country_id" class="text-danger mt-1">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>

                        <x-forms.text-input type="text" readonly name="slug" wire:model.live="slug"
                            label="Slug [autogenerated url]" />
                        @if ($university)
                            <small class="text-success">
                               will be visible to users via:
                                <b> 
                                    {{ url('/') }}/universities/{{ $slug }}
                                </b>
                            </small>
                        @endif
                        @error('slug')
                            <div id="slug" class="text-danger mt-1">
                                {{ $message }}
                            </div>
                        @enderror


                        <div class="col-12">
                            <button class="btn btn-soft-success btn-md me-2" type="submit">
                                <span class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"
                                    wire:loading></span>
                                Create record
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @include('components.alerts')
</div>
